[project]
name = "mcp-seo"
version = "0.1.0"
description = "MCP SEO - Professional SEO Analysis & Research Tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.2.0",
    "mcp>=1.13.0",
]
